name: YAML Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # You can specify the version you need

    - name: Install yamllint
      run: pip install yamllint

    - name: Run yamllint
      run: yamllint .

