name: YAML Linting

on:
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install yamllint
      run: |
        pip install yamllint
      shell: bash

    - name: Lint YAML files
      run: |
        echo "line-length: 120" > .yamllint
        yamllint . --config-file .yamllint --format=parsable 
      shell: bash
